definitions:
  steps:
    - step: &deploy
        name: deploy
        image: atlassian/default-image:3
        runs-on:
          - self.hosted
        script:
          - ./bitbucket_deploy.sh "$REMOTE_USER" "$REMOTE_HOST" "$ENVIRONMENT_CONTAINER" "$BITBUCKET_BRANCH" "$NODE_CONTAINER" "$BITBUCKET_COMMIT" "$SITE_DIR"

pipelines:
  pull-requests:
    '**':
      - parallel:
          - step:
              name: "PHPCS"
              runs-on:
                - self.hosted
              image: wodby/drupal-php:8.3-dev-4.61.2
              caches:
                - composer
              script:
                - git config --global --add safe.directory $BITBUCKET_CLONE_DIR
                - git fetch origin $BITBUCKET_BRANCH $BITBUCKET_PR_DESTINATION_BRANCH

                - composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
                - composer global config --no-plugins allow-plugins.phpro/grumphp true
                - composer global require drupal/coder:^8.3 --no-progress --prefer-dist
                - composer global require phpro/grumphp --no-interaction
                - export PATH="$PATH:$HOME/.composer/vendor/bin"

                - wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b ~/bin

                - |
                  if [ -n "$BITBUCKET_PR_ID" ]; then
                    # Get changed PHP-related files for pull requests
                    git diff --name-only origin/$BITBUCKET_BRANCH origin/$BITBUCKET_PR_DESTINATION_BRANCH > changed_files.txt
                  else
                    # For manual runs, check all PHP-related files under custom directories
                    find web/modules/custom/**/ web/themes/custom/**/ > changed_files.txt
                  fi
                  echo "Files that were changed:" && cat changed_files.txt

                - (cat changed_files.txt | grumphp run --tasks=phpcs 2> phpcs_report.txt) || true
                - |
                  if [ ! -s "phpcs_report.txt" ]; then
                    "PHPCS has not found any problems."
                    exit 0;
                  fi
                - cat phpcs_report.txt

                - |
                  if [ -n "$BITBUCKET_PR_ID" ]; then
                    ~/bin/reviewdog -f=checkstyle -name="PHPCS" -reporter=bitbucket-code-report -fail-level=any < phpcs_report.txt
                  elif [ -s phpcs_report.txt ]; then
                    echo "PHPCS found at least one issue"
                    exit 1;
                  fi

          - step:
              name: "ESLint"
              runs-on:
                - self.hosted
              image: wodby/drupal-php:8.3-dev-4.61.2
              caches:
                - node
              script:
                - git config --global --add safe.directory $BITBUCKET_CLONE_DIR
                - git fetch origin $BITBUCKET_BRANCH $BITBUCKET_PR_DESTINATION_BRANCH

                - composer global config --no-plugins allow-plugins.phpro/grumphp true
                - composer global require phpro/grumphp --no-interaction
                - export PATH="$PATH:$HOME/.composer/vendor/bin"

                - sudo apk add npm
                - sudo npm install

                - wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b ~/bin

                - |
                  if [ -n "$BITBUCKET_PR_ID" ]; then
                    # Get changed JS files for pull requests
                    git diff --name-only origin/$BITBUCKET_BRANCH origin/$BITBUCKET_PR_DESTINATION_BRANCH > changed_files.txt
                  else
                    # For manual runs, check all JS files under custom directories
                    find web/modules/custom/**/ web/themes/custom/**/ > changed_files.txt
                  fi
                  echo "Files that were changed:" && cat changed_files.txt

                - (cat changed_files.txt | grumphp run --tasks=eslint 2> eslint_report.txt) || true
                - cat eslint_report.txt

                - |
                  if [ -n "$BITBUCKET_PR_ID" ]; then
                    ~/bin/reviewdog -f=eslint -name="ESLint" -reporter=bitbucket-code-report -fail-level=any < eslint_report.txt
                  elif [ -s eslint_report.txt ]; then
                    echo "ESLint found at least one issue"
                    exit 1;
                  fi

          - step:
             name: "Trivy"
             runs-on:
                - self.hosted
             image: aquasec/trivy:latest
             script:
               - trivy fs --exit-code 1 --format table ./
  branches:
    master:
      - step:
          <<: *deploy
          deployment: Production

    '*.dev':
      - step:
          <<: *deploy
          deployment: Development
