version: '3.8'

services:
  db:
    image: mysql:8.0.39
    container_name: drupal-db-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password_root
      MYSQL_DATABASE: drupal_db
      MYSQL_USER: drupal_user
      MYSQL_PASSWORD: your_password
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql

  php:
    build: ./php
    container_name: drupal_php
    restart: always
    volumes:
      - ./drupal:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:1.24.0
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./drupal:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

volumes:
  db_data:
