services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "mariadb-dev"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_TRANSACTION_ISOLATION: READ-COMMITTED
    volumes:
      - /var/www/dev/back_sql/back_mariadb:/docker-entrypoint-initdb.d
      - mariadb-datavolume-dev:/var/lib/mysql

  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "php-dev"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - liqx_site:/var/www/html

  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "nginx-dev"
    depends_on:
      - "php"
    environment:
      NGINX_SET_REAL_IP_FROM: "0.0.0.0/0"
      NGINX_REAL_IP_HEADER: "CF-Connecting-IP"
      NGINX_REAL_IP_RECURSIVE: on
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php-dev
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
    volumes:
      - liqx_site:/var/www/html:cached
    ports:
      - "8000:80"

  memcached:
    image: wodby/memcached:$MEMCACHED_TAG
    container_name: "memcached-dev"
    environment:
      MEMCACHED_MEMORY_LIMIT: 64 # Memory limit in MB
      MEMCACHED_MAX_CONNECTIONS: 1024 # Maximum number of connections
    command: memcached -m 512 -t 4 -c 512 -vv
    labels:
      - "traefik.enable=false"

  node:
    image: wodby/node:$NODE_TAG
    container_name: "node-dev"
    working_dir: /var/www/html/web/themes/custom/bootcamp_theme
    volumes:
      - liqx_site:/var/www/html
    command: sh -c 'npm install && npm run build'

volumes:
  mariadb-datavolume-dev:
  liqx_site:
