# Use Ubuntu base image
FROM ubuntu:24.04

# Install required packages
RUN apt-get update && apt-get install -y \
    software-properties-common \
    curl \
    wget \
    git \
    unzip \
    zip \
    vim \
    && apt-get clean

# Install PHP and required PHP extensions
RUN apt-get install -y \
    php8.3 \
    php8.3-cli \
    php8.3-fpm \
    php8.3-mbstring \
    php8.3-xml \
    php8.3-mysql \
    php8.3-zip \
    php8.3-curl \
    php8.3-gd \
    php8.3-opcache \
    php8.3-intl \
    php-memcached

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Add Composer global bin to PATH
ENV PATH="$PATH:/root/.composer/vendor/bin"

# Clean up apt cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Create a directory for the PHP-FPM socket
RUN mkdir -p /run/php && chown www-data:www-data /run/php

# Configure PHP-FPM to listen on a Unix socket
COPY ./www.conf /etc/php/8.3/fpm/pool.d/www.conf

# Copy site files
COPY dev/ /var/www/html

# Set working directory
WORKDIR /var/www/html

# Install all dependencies
RUN composer install

# Start PHP
CMD ["sh", "-c", "/var/www/html/vendor/bin/drush deploy -y && php-fpm8.3 -F"]
