services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_TRANSACTION_ISOLATION: READ-COMMITTED
    volumes:
      - /var/www/html/back_sql:/docker-entrypoint-initdb.d
      - mariadb-datavolume:/var/lib/mysql

  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "php"
    environment:
      PHP_EXTENSIONS_DISABLE: xhprof,spx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/www/html:/var/www/html:cached
      - php_ssh:/home/wodby/.ssh

  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
    volumes:
      - /var/www/html:/var/www/html:cached
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`www.drupalliqx.pp.ua`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=myresolver"

  node:
    image: wodby/node:$NODE_TAG
    container_name: "node"
    working_dir: /var/www/html/web/themes/custom/bootcamp_theme
    volumes:
      - /var/www/html:/var/www/html
    command: sh -c 'npm install && npm run start'

networks:
  default:
    external:
      name: traefik-net

volumes:
  mariadb-datavolume:
    driver: local
  php_ssh:
    driver: local
