name: Deploy to Remote Server

on:
  push:
    branches:
      - 'R8492_Configuration_of_CD'


#  workflow_run:
#    workflows: [PHPCS Check]
#    types:
#      - completed

jobs:
  deploy_to_remote:
    runs-on: ubuntu-latest
   # if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/master'}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
            set -e

            # Variables
            DEPLOY_DIR="/var/www/html"
            REPO_URL="git@github.com:liqxDev/drupal_task.git"
            BRANCH="master"

            # Clean up the old deployment if it exists
            if [ -d "$DEPLOY_DIR" ]; then
              rm -rf "$DEPLOY_DIR"
            fi

            # Clone the repository
            git clone -b $BRANCH $REPO_URL $DEPLOY_DIR
            # Navigate to the deployment directory
            cd /var/www/html || exit
            composer update

            # Install dependencies (e.g., via Composer)
            chmod -R 755 /var/www/
            chown www-data:www-data -R /var/www/html
            runuser -u www-data -- composer install --no-dev --optimize-autoloader

        env:
          SSH_USER: ${{ secrets.REMOTE_USER }}
          SSH_HOST: ${{ secrets.REMOTE_SERVER }}

