name: PHPCS Check

# Triggers the workflow on push, commit, and pull request events
on:
  push:
    branches:
      - '**' # This will trigger on any branch push
  pull_request:
    branches:
      - '**' # This will trigger on any branch PR creation or updates

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Check if Prisma schema changed
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

    - name: Run PHPCS on changed files
      run: |
        if [[ -s changed_files.txt && $(cat changed_files.txt | wc -l) -gt 0 ]]; then
          vendor/bin/phpcs $(cat changed_files.txt) --extensions=php,install,module,theme
        else
          echo "No PHP files changed. Skipping PHPCS."
        fi
