name: PHPCS Check

# Triggers the workflow on push, commit, and pull request events
on:
  push:
    branches:
      - '**' # This will trigger on any branch push
  pull_request:
    branches:
      - '**' # This will trigger on any branch PR creation or updates

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Determine base reference
      id: determine_base_ref
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          echo "::set-output name=BASE_REF::${{ github.event.pull_request.base.sha }}"
        else
          echo "::set-output name=BASE_REF::${{ github.sha }}^"
        fi

    - name: Get list of changed files
      id: changed_files
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          git diff --name-only --diff-filter=d ${{ github.event.pull_request.base.sha }} -- 'web/themes/custom/*' 'web/modules/custom/*' > changed_files.txt
        else
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            git diff --name-only --diff-filter=d HEAD^ -- 'web/themes/custom/*' 'web/modules/custom/*' > changed_files.txt
          else
            echo "First commit or orphan branch, no previous commit to compare to." > changed_files.txt
          fi
        fi

    - name: Run PHPCS on changed files
      run: |
        if [[ -s changed_files.txt && $(cat changed_files.txt | wc -l) -gt 0 ]]; then
          vendor/bin/phpcs $(cat changed_files.txt) --extensions=php,install,module,theme
        else
          echo "No PHP files changed. Skipping PHPCS."
        fi
