name: PHPCS Check


# Triggers the workflow on push, commit, and pull request events
on:
  push:
    branches:
      - '**' # This will trigger on any branch push
  pull_request:
    branches:
      - '**' # This will trigger on any branch PR creation or updates

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Get changed PHP files
      id: changed_files
      run: |
        git fetch origin ${{ github.event.pull_request.base.sha }} --depth=1
        git diff --name-only ${{ github.event.pull_request.base.sha }} HEAD | grep -E '\.php$|\.install$|\.module$|\.theme$' > changed_files.txt || true

    - name: Run PHPCS on changed files
      run: |
        if [ -s changed_files.txt ]; then
          vendor/bin/phpcs $(cat changed_files.txt)
        else
          echo "No PHP files changed, skipping PHPCS."
        fi
